// ============================================================
// providers/lyrics_provider.dart
// ============================================================

import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../models/song.dart';
import '../services/lrclib_service.dart';
import '../services/youtube_service.dart';
import 'player_provider.dart';

// ─── State ───────────────────────────────────────────────────────────────────

class LyricsState {
  final String? videoId;
  final bool isLoading;
  final String? error;
  final List<LyricLine> lines;

  /// Where the lyrics came from — displayed in the footer.
  final LyricsSource source;

  // Available caption tracks for the current video (empty = only one/none)
  final List<CaptionTrackInfo> availableTracks;
  // The currently selected track code (null = default auto-pick)
  final String? selectedTrackCode;

  const LyricsState({
    this.videoId,
    this.isLoading = false,
    this.error,
    this.lines = const [],
    this.source = LyricsSource.none,
    this.availableTracks = const [],
    this.selectedTrackCode,
  });

  bool get hasLyrics => lines.isNotEmpty;

  bool get isArabic =>
      selectedTrackCode?.toLowerCase().split('-').first == 'ar';

  /// The label of the currently selected track, or null.
  String? get selectedTrackLabel => availableTracks
      .where((t) => t.code == selectedTrackCode)
      .map((t) => t.label)
      .firstOrNull;

  LyricsState copyWith({
    String? videoId,
    bool? isLoading,
    String? error,
    List<LyricLine>? lines,
    LyricsSource? source,
    List<CaptionTrackInfo>? availableTracks,
    String? selectedTrackCode,
    bool clearError = false,
    bool clearSelectedTrack = false,
  }) {
    return LyricsState(
      videoId: videoId ?? this.videoId,
      isLoading: isLoading ?? this.isLoading,
      error: clearError ? null : (error ?? this.error),
      lines: lines ?? this.lines,
      source: source ?? this.source,
      availableTracks: availableTracks ?? this.availableTracks,
      selectedTrackCode: clearSelectedTrack
          ? null
          : (selectedTrackCode ?? this.selectedTrackCode),
    );
  }
}

// ─── Source tag ──────────────────────────────────────────────────────────────

enum LyricsSource { none, youtube, lrclib, lrclibPlain }

// ─── Notifier ────────────────────────────────────────────────────────────────

class LyricsNotifier extends StateNotifier<LyricsState> {
  final YoutubeService _yt;
  final LrclibService _lrclib;

  LyricsNotifier(this._yt, this._lrclib) : super(const LyricsState());

  /// Fetch lyrics for a new video.
  ///
  /// Strategy:
  ///   1. LRCLIB synced/plain lyrics     → best match, no robot noise
  ///   2. Manual YT captions             → human-written subtitles
  ///   3. Auto-generated YT captions     → last resort
  ///   4. Nothing found                  → show "No lyrics available"
  Future<void> fetchFor(String videoId, {Song? song}) async {
    // Only skip if already loaded (not errored) for same video
    if (state.videoId == videoId && !state.isLoading && state.hasLyrics) {
      return;
    }

    state = LyricsState(videoId: videoId, isLoading: true);

    try {
      // Fetch YT caption tracks and LRCLIB in parallel
      List<CaptionTrackInfo> tracks = [];
      List<LyricLine> lrcLines = [];

      await Future.wait([
        () async {
          try { tracks = await _yt.getAvailableCaptionTracks(videoId); } catch (_) {}
        }(),
        () async {
          if (song == null) return;
          try { lrcLines = await _lrclib.fetchForSong(song); } catch (_) {}
        }(),
      ]);

      if (!mounted) return;

      // Split tracks by type
      final manualTracks = tracks.where((t) => !t.isAutoGenerated).toList();
      final autoTracks   = tracks.where((t) => t.isAutoGenerated).toList();

      if (lrcLines.isNotEmpty) {
        // ── 1. LRCLIB ────────────────────────────────────────────────
        final isSynced = LrclibService.hasSyncedLyrics(lrcLines);
        state = LyricsState(
          videoId: videoId,
          isLoading: false,
          lines: lrcLines,
          source: isSynced ? LyricsSource.lrclib : LyricsSource.lrclibPlain,
        );
      } else if (manualTracks.isNotEmpty) {
        // ── 2. Manual YT captions ─────────────────────────────────────
        final eng = manualTracks.firstWhere(
          (t) => t.code.startsWith('en'),
          orElse: () => manualTracks.first,
        );
        final lines = await _yt.getLyricsForTrack(videoId, eng.code);
        if (!mounted) return;
        state = LyricsState(
          videoId: videoId,
          isLoading: false,
          lines: lines,
          source: LyricsSource.youtube,
          availableTracks: tracks,
          selectedTrackCode: eng.code,
          error: lines.isEmpty ? 'No lyrics available for this song.' : null,
        );
      } else if (autoTracks.isNotEmpty) {
        // ── 3. Auto-generated YT captions (last resort) ───────────────
        final eng = autoTracks.firstWhere(
          (t) => t.code.startsWith('en'),
          orElse: () => autoTracks.first,
        );
        final lines = await _yt.getLyricsForTrack(videoId, eng.code);
        if (!mounted) return;
        state = LyricsState(
          videoId: videoId,
          isLoading: false,
          lines: lines,
          source: LyricsSource.youtube,
          availableTracks: tracks,
          selectedTrackCode: eng.code,
          error: lines.isEmpty ? 'No lyrics available for this song.' : null,
        );
      } else {
        // ── 4. Nothing found ─────────────────────────────────────────
        state = LyricsState(
          videoId: videoId,
          isLoading: false,
          error: 'No lyrics available for this song.',
        );
      }
    } catch (e) {
      if (!mounted) return;
      state = LyricsState(
        videoId: videoId,
        isLoading: false,
        error: 'Failed to load lyrics: $e',
      );
    }
  }

  /// Switch to a different YouTube caption track.
  Future<void> selectTrack(String languageCode) async {
    final videoId = state.videoId;
    if (videoId == null) return;
    if (state.selectedTrackCode == languageCode) return;

    state = state.copyWith(isLoading: true, selectedTrackCode: languageCode);

    try {
      final lines = await _yt.getLyricsForTrack(videoId, languageCode);
      if (!mounted) return;
      state = state.copyWith(
        isLoading: false,
        lines: lines,
        source: LyricsSource.youtube,
        selectedTrackCode: languageCode,
        error: lines.isEmpty ? 'No lyrics for this track.' : null,
        clearError: lines.isNotEmpty,
      );
    } catch (e) {
      if (!mounted) return;
      state = state.copyWith(
        isLoading: false,
        error: 'Failed to load track: $e',
      );
    }
  }

  void clear() => state = const LyricsState();
}

// ─── Providers ───────────────────────────────────────────────────────────────

final lyricsProvider =
    StateNotifierProvider<LyricsNotifier, LyricsState>((ref) {
  final handler = ref.watch(audioHandlerProvider);
  return LyricsNotifier(
    handler.service.youtubeService,
    LrclibService(),
  );
});
