// GENERATED CODE - DO NOT MODIFY BY HAND
// This file is auto-generated by hive_generator.
// Run: flutter pub run build_runner build

part of 'song.dart';

// **************************************************************************
// TypeAdapterGenerator
// **************************************************************************

class SongAdapter extends TypeAdapter<Song> {
  @override
  final int typeId = 0;

  @override
  Song read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return Song(
      id: fields[0] as String,
      title: fields[1] as String,
      channelName: fields[2] as String,
      thumbnailUrl: fields[3] as String,
      duration: Duration(milliseconds: fields[4] as int),
      streamUrl: fields[5] as String?,
      streamUrlFetchedAt: fields[6] as DateTime?,
      isLocal: fields[7] == true,       // default false for old records
      localPath: fields[8] as String?,
    );
  }

  @override
  void write(BinaryWriter writer, Song obj) {
    writer
      ..writeByte(9)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.title)
      ..writeByte(2)
      ..write(obj.channelName)
      ..writeByte(3)
      ..write(obj.thumbnailUrl)
      ..writeByte(4)
      ..write(obj.duration.inMilliseconds)
      ..writeByte(5)
      ..write(obj.streamUrl)
      ..writeByte(6)
      ..write(obj.streamUrlFetchedAt)
      ..writeByte(7)
      ..write(obj.isLocal)
      ..writeByte(8)
      ..write(obj.localPath);
  }

  @override
  int get hashCode => typeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SongAdapter &&
          runtimeType == other.runtimeType &&
          typeId == other.typeId;
}
