// File generated by FlutterFire CLI — do not edit manually.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGFYdmV8MpsbLMUV-A_gD1X9GFfOI3iwU',
    appId: '1:210995583890:android:c32b1e0dea4386c1a57f4b',
    messagingSenderId: '210995583890',
    projectId: 'ytspotify-aa97c',
    storageBucket: 'ytspotify-aa97c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDv9l7X2dHeQTIjCWUVWA_cWTI5wy3QoJc',
    appId: '1:210995583890:web:24ac64e698e2637ba57f4b',
    messagingSenderId: '210995583890',
    projectId: 'ytspotify-aa97c',
    authDomain: 'ytspotify-aa97c.firebaseapp.com',
    storageBucket: 'ytspotify-aa97c.firebasestorage.app',
    measurementId: 'G-46MLBNTJX2',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv9l7X2dHeQTIjCWUVWA_cWTI5wy3QoJc',
    appId: '1:210995583890:web:24ac64e698e2637ba57f4b',
    messagingSenderId: '210995583890',
    projectId: 'ytspotify-aa97c',
    authDomain: 'ytspotify-aa97c.firebaseapp.com',
    storageBucket: 'ytspotify-aa97c.firebasestorage.app',
    measurementId: 'G-46MLBNTJX2',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGFYdmV8MpsbLMUV-A_gD1X9GFfOI3iwU',
    appId: '1:210995583890:ios:c32b1e0dea4386c1a57f4b',
    messagingSenderId: '210995583890',
    projectId: 'ytspotify-aa97c',
    storageBucket: 'ytspotify-aa97c.firebasestorage.app',
    iosBundleId: 'com.example.testf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGFYdmV8MpsbLMUV-A_gD1X9GFfOI3iwU',
    appId: '1:210995583890:macos:c32b1e0dea4386c1a57f4b',
    messagingSenderId: '210995583890',
    projectId: 'ytspotify-aa97c',
    storageBucket: 'ytspotify-aa97c.firebasestorage.app',
    iosBundleId: 'com.example.testf',
  );
}
