/**
 * LyricsPanel.jsx
 *
 * Full-screen overlay — exact match of desktop lyrics_panel.dart
 *
 *  ┌──────────────────────┬────────────────────────────────┐
 *  │                      │  Song title                    │
 *  │  Thumbnail /         │  Artist                        │
 *  │  album art           │  [Lyrics] chip                 │
 *  │  (left column,       ├────────────────────────────────┤
 *  │   fills height,      │  lyric line 1                  │
 *  │   always visible)    │  lyric line 2  (scrollable)    │
 *  │                      │  …                             │
 *  └──────────────────────┴────────────────────────────────┘
 *
 * • Left column width is resizable (drag the divider).
 * • Lyrics scroll independently — thumbnail never moves.
 * • Active line auto-scrolls to 38% from top.
 * • Karaoke word-by-word highlight when word timing available.
 * • Past lines shown dimmer than future lines.
 * • × close button pinned top-right.
 */

import { useEffect, useRef, useState, forwardRef } from 'react'
import { X, Music2, Mic2, ChevronDown, Check } from 'lucide-react'
import { usePlayerStore, PanelMode } from '../../stores/playerStore'
import { fetchLyricsForSong } from '../../services/lyricsService'
import { getCaptionTracks, getCaptionTrack } from '../../services/youtubeService'

// ── Constants ─────────────────────────────────────────────────────────────────
const LEFT_MIN     = 220
const LEFT_MAX     = 600
const LEFT_DEFAULT = 340
const DIVIDER_W    = 8

// ── Main ──────────────────────────────────────────────────────────────────────

export default function LyricsPanel() {
  const currentSong = usePlayerStore((s) => s.currentSong)
  const position    = usePlayerStore((s) => s.position)
  const setPanelMode = usePlayerStore((s) => s.setPanelMode)

  // ── Left column width (resizable) ─────────────────────────────────────────
  const [leftW, setLeftW] = useState(LEFT_DEFAULT)
  const leftWRef = useRef(leftW)
  leftWRef.current = leftW

  function onDividerMouseDown(e) {
    e.preventDefault()
    const startX = e.clientX
    const startW = leftWRef.current
    function onMove(e2) {
      const newW = Math.max(LEFT_MIN, Math.min(LEFT_MAX, startW + (e2.clientX - startX)))
      setLeftW(newW)
    }
    function onUp() {
      window.removeEventListener('mousemove', onMove)
      window.removeEventListener('mouseup', onUp)
    }
    window.addEventListener('mousemove', onMove)
    window.addEventListener('mouseup', onUp)
  }

  // ── Lyrics state ──────────────────────────────────────────────────────────
  const [lyricsState, setLyricsState] = useState({ lines: [], loading: false, error: null })
  const [lyricsSource, setLyricsSource] = useState('yt') // 'yt' | 'lrclib'
  const [tracks,      setTracks]      = useState([])
  const [selTrack,    setSelTrack]    = useState(null)
  const [trackMenuOpen, setTrackMenuOpen] = useState(false)
  const lastSongIdRef = useRef(null)
  const scrollRef     = useRef(null)
  const lineRefs      = useRef([])
  const [activeIdx, setActiveIdx] = useState(-1)
  const activeIdxRef = useRef(-1)

  useEffect(() => {
    if (!currentSong || currentSong.id === lastSongIdRef.current) return
    lastSongIdRef.current = currentSong.id
    setActiveIdx(-1); activeIdxRef.current = -1
    lineRefs.current = []
    if (scrollRef.current) scrollRef.current.scrollTop = 0
    setTracks([]); setSelTrack(null)
    setLyricsState({ lines: [], loading: true, error: null })
    setLyricsSource('yt')

    Promise.all([
      getCaptionTracks(currentSong.id).catch(() => []),
      fetchLyricsForSong(currentSong).catch(() => ({ parsed: [] })),
    ]).then(([ytTracks, lrcResult]) => {
      setTracks(ytTracks)

      const manualTracks = ytTracks.filter((t) => !t.isAutoGenerated)
      const autoTracks   = ytTracks.filter((t) => t.isAutoGenerated)

      if (lrcResult.parsed?.length) {
        // ── 1. LRCLIB (synced/plain) ──────────────────────────────────
        setLyricsSource('lrclib')
        setLyricsState({ lines: lrcResult.parsed, loading: false, error: null })
      } else if (manualTracks.length) {
        // ── 2. Manual YT captions ─────────────────────────────────────
        const eng  = manualTracks.find((t) => t.code.startsWith('en')) || manualTracks[0]
        const code = eng?.code
        setSelTrack(code); setLyricsSource('yt')
        if (code) {
          getCaptionTrack(currentSong.id, code)
            .then((lines) => setLyricsState({ lines, loading: false, error: lines.length ? null : 'No lyrics available.' }))
            .catch(() => setLyricsState({ lines: [], loading: false, error: 'No lyrics available.' }))
        } else {
          setLyricsState({ lines: [], loading: false, error: 'No lyrics available.' })
        }
      } else if (autoTracks.length) {
        // ── 3. Auto-generated YT captions (last resort) ───────────────
        const eng  = autoTracks.find((t) => t.code.startsWith('en')) || autoTracks[0]
        const code = eng?.code
        setSelTrack(code); setLyricsSource('yt')
        if (code) {
          getCaptionTrack(currentSong.id, code)
            .then((lines) => setLyricsState({ lines, loading: false, error: lines.length ? null : 'No lyrics available.' }))
            .catch(() => setLyricsState({ lines: [], loading: false, error: 'No lyrics available.' }))
        } else {
          setLyricsState({ lines: [], loading: false, error: 'No lyrics available.' })
        }
      } else {
        setLyricsState({ lines: [], loading: false, error: 'No lyrics available for this song.' })
      }
    }).catch(() => {
      setLyricsState({ lines: [], loading: false, error: 'No lyrics available for this song.' })
    })
  }, [currentSong?.id])

  async function switchTrack(code) {
    if (code === selTrack) return
    setSelTrack(code); setTrackMenuOpen(false)
    setLyricsSource('yt')
    setLyricsState((s) => ({ ...s, loading: true, error: null }))
    try {
      const lines = await getCaptionTrack(currentSong.id, code)
      setLyricsState({ lines, loading: false, error: lines.length ? null : 'No lyrics for this language.' })
    } catch {
      setLyricsState((s) => ({ ...s, loading: false, error: 'Failed to load this language.' }))
    }
  }

  // Sync active line with position
  useEffect(() => {
    const lines = lyricsState.lines
    if (!lines.length) return
    let active = -1
    for (let i = 0; i < lines.length; i++) {
      if (position >= lines[i].time) active = i
    }
    if (active !== activeIdxRef.current) {
      activeIdxRef.current = active
      setActiveIdx(active)
      scrollToActive(active)
    }
  }, [position, lyricsState.lines])

  function scrollToActive(index) {
    if (index < 0) return
    const el = lineRefs.current[index]
    const container = scrollRef.current
    if (!el || !container) return
    // Schedule after paint so the ref is measured correctly
    requestAnimationFrame(() => {
      const containerTop = container.getBoundingClientRect().top
      const lineTop = el.getBoundingClientRect().top
      const target = container.scrollTop + (lineTop - containerTop) - container.clientHeight * 0.38
      container.scrollTo({ top: Math.max(0, target), behavior: 'smooth' })
    })
  }

  function handleLineClick(time) {
    if (window.utifyPlayer?.seekTo) window.utifyPlayer.seekTo(time)
    usePlayerStore.getState().setPosition(time)
  }

  function handleClose() {
    setPanelMode(PanelMode.LYRICS)
  }

  // ── Render ────────────────────────────────────────────────────────────────
  return (
    <div style={styles.overlay}>
      <div style={styles.row}>

        {/* ── LEFT: thumbnail / album art ── */}
        <div style={{ width: leftW, flexShrink: 0, position: 'relative', overflow: 'hidden' }}>
          {currentSong?.thumbnailUrl ? (
            <>
              <img
                src={currentSong.thumbnailUrl}
                alt={currentSong.title}
                style={{ position: 'absolute', inset: 0, width: '100%', height: '100%', objectFit: 'cover' }}
              />
              {/* Right-edge fade */}
              <div style={{
                position: 'absolute', inset: 0,
                background: 'linear-gradient(to right, transparent 75%, rgba(0,0,0,0.8) 100%)',
              }} />
            </>
          ) : (
            <div style={{
              position: 'absolute', inset: 0, background: 'var(--color-card)',
              display: 'flex', alignItems: 'center', justifyContent: 'center',
            }}>
              <Music2 size={80} color='var(--color-subtext)' style={{ opacity: 0.12 }} />
            </div>
          )}
        </div>

        {/* ── DIVIDER ── */}
        <ColumnDivider onMouseDown={onDividerMouseDown} />

        {/* ── RIGHT: song info + scrollable lyrics ── */}
        <div style={styles.rightCol}>
          {/* Song info header */}
          {currentSong && (
            <div style={styles.songInfo}>
              <h2 style={styles.songTitle}>{currentSong.title}</h2>
              <p style={styles.songChannel}>{currentSong.channelName}</p>
              {/* "Lyrics" chip + language picker */}
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap', marginBottom: 16 }}>
                <div style={styles.lyricsChip}>
                  <Mic2 size={14} color='var(--color-button)' />
                  <span style={{ color: 'var(--color-button)', fontSize: 12, fontWeight: 700, marginLeft: 5 }}>
                    Lyrics
                  </span>
                </div>

                {/* Language switcher */}
                {tracks.length > 1 && (
                  <div style={{ position: 'relative' }}>
                    <button
                      onClick={() => setTrackMenuOpen((o) => !o)}
                      style={{
                        display: 'flex', alignItems: 'center', gap: 4,
                        padding: '4px 10px', borderRadius: 6,
                        background: 'var(--color-card)', border: '1px solid var(--color-shadow)',
                        color: 'var(--color-button)', cursor: 'pointer', fontSize: 11, fontWeight: 600,
                      }}
                    >
                      <span style={{ maxWidth: 140, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                        {tracks.find((t) => t.code === selTrack)?.label?.replace(' (auto-generated)', '') || 'Auto'}
                      </span>
                      <ChevronDown size={12} />
                    </button>
                    {trackMenuOpen && (
                      <LangMenu
                        tracks={tracks}
                        selected={selTrack}
                        onSelect={switchTrack}
                        onClose={() => setTrackMenuOpen(false)}
                      />
                    )}
                  </div>
                )}
              </div>
            </div>
          )}

          {/* Thin separator */}
          <div style={{ height: 1, background: 'var(--color-highlight)', margin: '0 0 0 0' }} />

          {/* Scrollable lyrics */}
          <div ref={scrollRef} style={styles.lyricsScroll}>
            {lyricsState.loading && (
              <div style={styles.center}>
                <div className="utify-spinner" />
                <span style={{ color: 'var(--color-subtext)', fontSize: 14, marginTop: 12 }}>
                  Loading lyrics…
                </span>
              </div>
            )}

            {!lyricsState.loading && !lyricsState.lines.length && (
              <div style={styles.center}>
                <Mic2 size={48} color='var(--color-misc)' />
                <span style={{ color: 'var(--color-subtext)', fontSize: 15, marginTop: 14, textAlign: 'center' }}>
                  {lyricsState.error || 'No lyrics available for this song.'}
                </span>
              </div>
            )}

            {lyricsState.lines.length > 0 && (
              <div style={{ padding: '0 20px 60px' }}>
                {lyricsState.lines.map((line, i) => (
                  <LyricLine
                    key={i}
                    ref={(el) => { lineRefs.current[i] = el }}
                    text={line.text}
                    words={line.words}
                    isActive={i === activeIdx}
                    isPast={i < activeIdx}
                    position={position}
                    onClick={() => handleLineClick(line.time)}
                  />
                ))}
                <p style={{ color: 'var(--color-shadow)', fontSize: 12, paddingTop: 28 }}>
                  {lyricsSource === 'lrclib' ? 'Lyrics provided by LRCLIB' : 'Lyrics provided by YouTube'}
                </p>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* ── Close button ── */}
      <button
        onClick={handleClose}
        aria-label="Close lyrics"
        style={styles.closeBtn}
        onMouseEnter={(e) => { e.currentTarget.style.background = 'rgba(255,255,255,0.15)' }}
        onMouseLeave={(e) => { e.currentTarget.style.background = 'rgba(255,255,255,0.1)' }}
      >
        <X size={18} color='var(--color-text)' />
      </button>

      <style>{`
        @keyframes utify-spin { to { transform: rotate(360deg); } }
        .utify-spinner {
          width: 28px; height: 28px; border-radius: 50%;
          border: 3px solid var(--color-highlight);
          border-top-color: var(--color-button);
          animation: utify-spin 0.7s linear infinite;
        }
      `}</style>
    </div>
  )
}

// ── LyricLine ─────────────────────────────────────────────────────────────────

const LyricLine = forwardRef(function LyricLine(
  { text, words, isActive, isPast, position, onClick }, ref
) {
  const color = isActive
    ? 'var(--color-text)'
    : isPast
      ? 'var(--color-shadow)'
      : 'var(--color-subtext)'

  const baseStyle = {
    fontSize: isActive ? 22 : 18,
    fontWeight: isActive ? 800 : 500,
    color,
    lineHeight: 1.3,
    marginBottom: 16,
    cursor: 'pointer',
    transition: 'font-size 220ms ease, font-weight 220ms ease, color 220ms ease',
  }

  // Karaoke word-by-word when active and word timing present
  if (isActive && words?.length) {
    return (
      <div ref={ref} style={{ ...baseStyle, display: 'flex', flexWrap: 'wrap', gap: '0 2px' }} onClick={onClick}>
        {words.map((word, i) => (
          <span
            key={i}
            style={{
              color: position >= word.time ? 'var(--color-button)' : 'rgba(255,255,255,0.45)',
              transition: 'color 120ms ease',
            }}
          >
            {word.text}&nbsp;
          </span>
        ))}
      </div>
    )
  }

  return (
    <div ref={ref} style={baseStyle} onClick={onClick}>
      {text}
    </div>
  )
})

// ── Column Divider ────────────────────────────────────────────────────────────

function ColumnDivider({ onMouseDown }) {
  const [hovered, setHovered] = useState(false)
  return (
    <div
      style={{
        width: DIVIDER_W, flexShrink: 0, cursor: 'col-resize',
        display: 'flex', alignItems: 'stretch', justifyContent: 'center',
      }}
      onMouseDown={onMouseDown}
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
    >
      <div style={{
        width: 2, height: '100%',
        background: hovered
          ? 'rgba(var(--color-button-rgb,29,185,84), 0.6)'
          : 'rgba(255,255,255,0.08)',
        transition: 'background 150ms',
      }} />
    </div>
  )
}

// ── LangMenu ──────────────────────────────────────────────────────────────────

function LangMenu({ tracks, selected, onSelect, onClose }) {
  const ref = useRef(null)
  useEffect(() => {
    function handler(e) { if (ref.current && !ref.current.contains(e.target)) onClose() }
    document.addEventListener('mousedown', handler)
    return () => document.removeEventListener('mousedown', handler)
  }, [onClose])

  return (
    <div ref={ref} style={{
      position: 'absolute', left: 0, top: '100%', marginTop: 4,
      background: 'var(--color-card)', border: '1px solid var(--color-shadow)',
      borderRadius: 8, minWidth: 200, zIndex: 400, boxShadow: '0 8px 24px rgba(0,0,0,0.5)',
      overflow: 'hidden',
    }}>
      {tracks.map((t) => (
        <button key={t.code} onClick={() => onSelect(t.code)} style={{
          display: 'flex', alignItems: 'center', gap: 8, width: '100%',
          padding: '9px 12px', background: 'none', border: 'none',
          color: t.code === selected ? 'var(--color-button)' : 'var(--color-text)',
          fontSize: 13, fontWeight: t.code === selected ? 700 : 400, cursor: 'pointer', textAlign: 'left',
        }}
          onMouseEnter={(e) => { e.currentTarget.style.background = 'var(--color-highlight)' }}
          onMouseLeave={(e) => { e.currentTarget.style.background = 'none' }}
        >
          <span style={{ width: 18, flexShrink: 0 }}>
            {t.code === selected && <Check size={14} color='var(--color-button)' />}
          </span>
          <span style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
            {t.label}{t.isAutoGenerated ? ' ✦' : ''}
          </span>
        </button>
      ))}
    </div>
  )
}

const styles = {
  overlay: {
    position: 'fixed',
    inset: 0,
    zIndex: 300,
    background: 'var(--color-main)',
    display: 'flex',
    flexDirection: 'column',
  },
  row: {
    flex: 1,
    display: 'flex',
    overflow: 'hidden',
    minHeight: 0,
  },
  rightCol: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    minWidth: 0,
  },
  songInfo: {
    padding: '20px 56px 0 20px',
    flexShrink: 0,
  },
  songTitle: {
    color: 'var(--color-text)',
    fontSize: 20,
    fontWeight: 800,
    margin: 0,
    lineHeight: 1.2,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
  },
  songChannel: {
    color: 'var(--color-subtext)',
    fontSize: 14,
    margin: '4px 0 14px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  lyricsChip: {
    display: 'inline-flex',
    alignItems: 'center',
    padding: '4px 10px',
    background: 'var(--color-card)',
    border: '1px solid var(--color-shadow)',
    borderRadius: 6,
  },
  lyricsScroll: {
    flex: 1,
    overflowY: 'auto',
    overflowX: 'hidden',
    scrollbarWidth: 'thin',
    scrollbarColor: 'var(--color-button) transparent',
  },
  center: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    padding: 32,
    minHeight: 300,
  },
  closeBtn: {
    position: 'absolute',
    top: 14,
    right: 14,
    width: 34,
    height: 34,
    borderRadius: '50%',
    background: 'rgba(255,255,255,0.1)',
    border: 'none',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'background 150ms',
    zIndex: 10,
  },
}
