/**
 * Utify Firebase Cloud Functions
 * Uses YouTube InnerTube API — no API key required.
 *
 * Exports:
 *   searchYouTube(query, pageToken?)       → { results, nextPageToken }
 *   getTrendingMusic(regionCode?)          → { results }
 *   getVideoStreamUrl(videoId)             → { url, muxedUrl, expiresAt }
 *   getCaptionTracks(videoId)              → { tracks: [{ code, label, isAutoGenerated }] }
 *   getCaptionTrack(videoId, languageCode) → { lines: [{ time, text, words? }] }
 */

class HttpsError extends Error { constructor(code, message) { super(message); this.code = code; } }

// ── InnerTube constants ───────────────────────────────────────────────────────

// In development: Vite proxies /youtubei → youtube.com
// In production:  requests go through the Cloudflare Worker proxy
// VITE_YT_PROXY is set in .env.production to the worker URL
const PROXY_BASE = import.meta.env.VITE_YT_PROXY || ''
const INNERTUBE_BASE = `${PROXY_BASE}/youtubei/v1`
const INNERTUBE_CLIENT = {
  hl:            'en',
  gl:            'US',
  clientName:    'WEB',
  clientVersion: '2.20240101.00.00',
}

const INNERTUBE_HEADERS = {
  'Content-Type':            'application/json',
  'User-Agent':              'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120.0.0.0 Safari/537.36',
  'Origin':                  'https://www.youtube.com',
  'Referer':                 'https://www.youtube.com/',
  'X-YouTube-Client-Name':   '1',
  'X-YouTube-Client-Version':'2.20240101.00.00',
}

function innerTubePayload(extra = {}, clientOverride = {}) {
  return {
    context: {
      client: { ...INNERTUBE_CLIENT, ...clientOverride },
    },
    ...extra,
  }
}

async function innerTubeFetch(endpoint, body) {
  const res = await fetch(`${INNERTUBE_BASE}/${endpoint}`, {
    method:  'POST',
    headers: INNERTUBE_HEADERS,
    body:    JSON.stringify(body),
  })
  if (!res.ok) throw new HttpsError('internal', `InnerTube HTTP ${res.status}`)
  return res.json()
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function getText(node) {
  if (!node) return ''
  if (typeof node.simpleText === 'string') return node.simpleText
  if (Array.isArray(node.runs)) return node.runs.map((r) => r.text || '').join('')
  return ''
}

function bestThumbnail(thumbnails) {
  if (!Array.isArray(thumbnails) || !thumbnails.length) return ''
  return thumbnails.sort((a, b) => (b.width || 0) - (a.width || 0))[0]?.url || ''
}

function parseDuration(text) {
  if (!text) return 0
  const parts = text.split(':').map(Number)
  if (parts.length === 3) return parts[0] * 3600 + parts[1] * 60 + parts[2]
  if (parts.length === 2) return parts[0] * 60 + parts[1]
  return parts[0] || 0
}

function videoRendererToSong(r) {
  if (!r) return null
  const id = r.videoId
  if (!id) return null
  const durationText = getText(r.lengthText)
  const durationSeconds = parseDuration(durationText)
  if (!durationSeconds) return null // filter live streams

  return {
    id,
    title:           getText(r.title),
    channelName:     getText(r.ownerText || r.shortBylineText || r.longBylineText),
    thumbnailUrl:    bestThumbnail(r.thumbnail?.thumbnails),
    durationSeconds,
  }
}

// ── searchYouTube ─────────────────────────────────────────────────────────────

export async function searchYouTubeParser(req) {
  const { query, pageToken } = req.data || {}
  if (!query || typeof query !== 'string' || !query.trim()) {
    throw new HttpsError('invalid-argument', 'query must be a non-empty string')
  }

  const body = innerTubePayload({ query: query.trim() })
  if (pageToken) body.continuation = pageToken

  const data = await innerTubeFetch('search', body)

  const results = []
  function walk(obj) {
    if (!obj || typeof obj !== 'object') return
    if (obj.videoRenderer) {
      const song = videoRendererToSong(obj.videoRenderer)
      if (song) results.push(song)
      return
    }
    if (Array.isArray(obj)) { obj.forEach(walk); return }
    Object.values(obj).forEach(walk)
  }

  const contents = data?.contents?.twoColumnSearchResultsRenderer
    ?.primaryContents?.sectionListRenderer?.contents
  if (contents) walk(contents)

  const nextPageToken =
    data?.onResponseReceivedCommands?.[0]?.appendContinuationItemsAction
      ?.continuationItems?.find((c) => c.continuationItemRenderer)
      ?.continuationItemRenderer?.continuationEndpoint?.continuationCommand?.token || null

  return { results: results.slice(0, 20), nextPageToken }
}

// ── getTrendingMusic ──────────────────────────────────────────────────────────

export async function getTrendingMusicParser(req) {
  const { regionCode } = req.data || {}
  const clientOverride = regionCode ? { gl: regionCode.toUpperCase() } : {}
  const body = innerTubePayload({ browseId: 'FEmusic_charts' }, clientOverride)
  const data = await innerTubeFetch('browse', body)

  const results = []
  function extractVideos(obj) {
    if (!obj || typeof obj !== 'object') return
    if (obj.videoRenderer) {
      const song = videoRendererToSong(obj.videoRenderer)
      if (song) results.push(song)
      return
    }
    if (Array.isArray(obj)) { obj.forEach(extractVideos); return }
    Object.values(obj).forEach(extractVideos)
  }
  extractVideos(data)

  return { results: results.slice(0, 20) }
}

// ── getVideoStreamUrl ─────────────────────────────────────────────────────────
// Returns the best muxed (video+audio) MP4 stream URL for a video.
// The web client strips the audio when we mute the element, giving us
// a silent visual-only preview (mirrors VideoPreviewWidget in Flutter).

export async function getVideoStreamUrlParser(req) {
  const { videoId } = req.data || {}
  if (!videoId || typeof videoId !== 'string') {
    throw new HttpsError('invalid-argument', 'videoId is required')
  }

  // Use the Android InnerTube client — it returns downloadable stream URLs
  const body = {
    context: {
      client: {
        hl:            'en',
        gl:            'US',
        clientName:    'ANDROID',
        clientVersion: '19.09.37',
        androidSdkVersion: 30,
      },
    },
    videoId,
    contentCheckOk: true,
    racyCheckOk:    true,
  }

  const res = await fetch(`${INNERTUBE_BASE}/player`, {
    method:  'POST',
    headers: {
      ...INNERTUBE_HEADERS,
      'X-YouTube-Client-Name':    '3',
      'X-YouTube-Client-Version': '19.09.37',
    },
    body: JSON.stringify(body),
  })
  if (!res.ok) throw new HttpsError('internal', `Player fetch failed: ${res.status}`)
  const data = await res.json()

  const formats  = data?.streamingData?.formats || []
  const adaptive = data?.streamingData?.adaptiveFormats || []
  const all      = [...formats, ...adaptive]

  // Prefer muxed mp4 (itag 18 = 360p mp4, 22 = 720p mp4)
  const muxed = formats
    .filter((f) => f.mimeType?.startsWith('video/mp4') && f.url)
    .sort((a, b) => (b.height || 0) - (a.height || 0))

  // Fallback: any video format
  const anyVideo = all
    .filter((f) => f.mimeType?.startsWith('video/') && f.url)
    .sort((a, b) => (b.height || 0) - (a.height || 0))

  const best = muxed[0] || anyVideo[0]
  if (!best?.url) throw new HttpsError('not-found', 'No stream URL found')

  // Parse expiry from the URL (expire= param)
  const expireMatch = best.url.match(/expire=(\d+)/)
  const expiresAt   = expireMatch ? parseInt(expireMatch[1]) * 1000 : Date.now() + 6 * 3600 * 1000

  return {
    url:       best.url,
    mimeType:  best.mimeType,
    width:     best.width || 0,
    height:    best.height || 0,
    expiresAt,
  }
}

// ── getCaptionTracks ──────────────────────────────────────────────────────────
// Returns all available caption/subtitle tracks for a video.

export async function getCaptionTracksParser(req) {
  const { videoId } = req.data || {}
  if (!videoId || typeof videoId !== 'string') {
    throw new HttpsError('invalid-argument', 'videoId is required')
  }

  const body = innerTubePayload({ videoId })
  const data = await innerTubeFetch('player', body)

  const captionTracks = data?.captions?.playerCaptionsTracklistRenderer?.captionTracks || []

  const tracks = captionTracks.map((t) => ({
    code:            t.languageCode || '',
    label:           getText(t.name) || t.languageCode || '',
    isAutoGenerated: t.kind === 'asr',
    baseUrl:         t.baseUrl ? t.baseUrl.replace("https://www.youtube.com", "") : '',  // used internally by getCaptionTrack
  }))

  return { tracks }
}

// ── getCaptionTrack ───────────────────────────────────────────────────────────
// Fetches and parses the timed text XML for a specific language track.
// Returns lines: [{ time (seconds), text, words?: [{ time, text }] }]

export async function getCaptionTrackParser(req) {
  const { videoId, languageCode } = req.data || {}
  if (!videoId || !languageCode) {
    throw new HttpsError('invalid-argument', 'videoId and languageCode are required')
  }

  // First get the track list to find the baseUrl.replace("https://www.youtube.com", "") for this language
  const body = innerTubePayload({ videoId })
  const data = await innerTubeFetch('player', body)

  const captionTracks = data?.captions?.playerCaptionsTracklistRenderer?.captionTracks || []
  const track = captionTracks.find((t) => t.languageCode === languageCode)
    || captionTracks.find((t) => t.languageCode?.startsWith(languageCode.split('-')[0]))

  if (!track?.baseUrl.replace("https://www.youtube.com", "")) {
    // Try to find any track as fallback
    if (!captionTracks.length) throw new HttpsError('not-found', 'No captions available')
    // Use first available track
    const fallback = captionTracks[0]
    return await fetchAndParseCaption(fallback.baseUrl.replace("https://www.youtube.com", ""), fallback.languageCode)
  }

  return await fetchAndParseCaption(track.baseUrl.replace("https://www.youtube.com", ""), languageCode)
}

async function fetchAndParseCaption(baseUrl, languageCode) {
  // Request JSON3 format (easier to parse than XML)
  // Route through proxy in production — replace youtube.com origin with proxy base
  const path = baseUrl.replace('https://www.youtube.com', '')
  const url = `${PROXY_BASE}${path}&fmt=json3&xorb=2&xobt=3&xovt=3`
  const res = await fetch(url, {
    headers: { 'User-Agent': INNERTUBE_HEADERS['User-Agent'] },
  })
  if (!res.ok) throw new HttpsError('internal', `Caption fetch failed: ${res.status}`)
  const data = await res.json()

  const events = data?.events || []
  const lines = []

  for (const event of events) {
    if (!event.segs || event.tStartMs === undefined) continue

    // tStartMs = start time in ms
    const time = event.tStartMs / 1000

    // segs is an array of word segments
    const segs = event.segs

    // Build full text
    const text = segs.map((s) => s.utf8 || '').join('').replace(/\n/g, ' ').trim()
    if (!text) continue

    // Word-level timing (if available — only in auto-generated captions)
    const words = segs
      .filter((s) => s.utf8?.trim() && s.tOffsetMs !== undefined)
      .map((s) => ({
        text: s.utf8.trim(),
        time: (event.tStartMs + (s.tOffsetMs || 0)) / 1000,
      }))

    lines.push({
      time,
      text,
      words: words.length > 1 ? words : undefined,
    })
  }

  return { lines, languageCode }
}


